### ISSUE TITLE
left align set labels 

### ISSUE THREAD

**Issue by trebor** [upsetjs/upsetjs#40]
i've been a huge fan of UpSet since i saw the demo at [IEEE Vis back in 2014](https://twitter.com/trebor/status/533197924944326656) and it's great to have such a versatile version!

currently the labels for sets, classed `setTextStyle-upset-*`, are `text-anchor: middle;` and clipped.  if the set names happen to not fit in the allotted space, they become unreadable because the front of the label is trimmed off.  if these labels where left aligned i think the chart would be more usable with long labels.

if i manually trim the length of the set names then the hover text is also trimmed, so my users can't actually see the full name of the set.

if i hack the css: 

```css
[class*="setTextStyle-upset"] {
    text-anchor: start;
    transform: translate(-40px, 0px);
}
```
the clip box doesn't translate with the text and cut's the text off.

**Comment by sgratzl** [comment]
hi,
thx for your suggestion. It is true for long labels cutting them off at both ends doesn't make much sense. I think about it. 

In the meantime you would need to hack also the clip path the is performing the clipping operation. I assume you can find it with this CSS selector:

```css
[id*="clip-upset"] rect {
  transform: translate(-40px, 0px);
}
```
